### ISSUE TITLE
Provide capability to use multiple storage accounts

### ISSUE THREAD

**Issue by tomkerkhove** [scale-tone/DurableFunctionsMonitor#106]
We want to use one instance of Durable Functions Monitor and use it to monitor all our Azure Function Apps.

Our early thinking was to consolidate all Azure Function Apps on one storage account to leverage this but based on https://github.com/scale-tone/DurableFunctionsMonitor/discussions/99#discussioncomment-868524 it turns out that this is not recommended given it can have performance impact.

Because of this, it would be great if Durable Functions Monitor would support monitoring multiple storage accounts to act as a single-source-of-truth.

**Comment by scale-tone** [comment]
This indeed seems to be the most popular ask ([one](https://github.com/scale-tone/DurableFunctionsMonitor/issues/29), [two](https://github.com/scale-tone/DurableFunctionsMonitor/issues/95)), so I'll leave this one as open.

The answer is still the same: sadly it's hardly possible, since DfMon is itself a Durable Function (in a 'readonly' mode), and Durable Functions are unable to switch between storage accounts and/or to connect to multiple storage accounts. Each Functions host instance is anchored to a one and only one storage.

There was recently a [PR commited](https://github.com/Azure/azure-functions-durable-extension/pull/1125), which claims to allow DurableClient instances to be created on-the-fly (instead of being forcibly injected by the runtime). This theoretically would allow to overcome this limitation. Needs experimenting and subsequent extensive refactoring of [the backend](https://github.com/scale-tone/DurableFunctionsMonitor/tree/master/durablefunctionsmonitor.dotnetbackend).

Until then options are:
1. Deploy multiple DfMon instances, one per each account (probably, to the same App Service plan aka into the same computing instance, to reduce costs).
2. Automate deployment and run DfMon [as container instances](https://hub.docker.com/r/scaletone/durablefunctionsmonitor/tags?page=1&ordering=last_updated) in Kubernetes, ACI or wherever. [AKS deployment YAML included](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/dfm-aks-deployment.yaml).
3. Run DfMon along with your running Functions instance, aka [run it in 'injected' mode](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/NUGET_README.md#how-to-use).
4. Use DfMon as [VsCode extension](https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor) - there you can connect to any number of storages from the same VsCode window.

**Comment by tomkerkhove** [comment]
Thanks a ton, that's what I was afraid of!

**Comment by scale-tone** [comment]
Implemented in [v5.0](https://github.com/scale-tone/DurableFunctionsMonitor/releases/tag/v5.0). Please, validate.
