### ISSUE TITLE
Liquid Templates error on Durable Entity (404)

### ISSUE THREAD

**Issue by SamVanhoutte** [scale-tone/DurableFunctionsMonitor#49]
Hello, 

Just wanted to try out the Liquid template feature for a Durable Entity I have.  I am running a local docker container with 3.9 tag.

This is the error I get, when clicking the new tab of my template: `Failed to load Sequence Diagram: Request failed with status code 404`.

These are the steps I took:

1. Created a new file with name `overview.stockwatchentity.liquid`
2. Contents of the file: 
  ```liquid
  <h2>Details for {{Input.state.StockItemData.Ticker}}</h2>
  ```
3. I copied the file to my storage account: container `durable-functions-monitor` and subfolder `tab-templates`
4. I restarted the local container and when clicking the Durable Entity, I can see a new tab appear on my Durable Entity with the name OVERVIEW.
5. When clicking that overview tab, I get the error `Failed to load Sequence Diagram: Request failed with status code 404`.

Not sure if it's related to the liquid templates (as error message seems to be about sequence diagram), but before I configured the liquid template, it just worked.

The current state of my Entity: 
```json
{
   "exists": true,
   "state": "{\"StockItemData\":{\"Isin\":\"BE0974268972\",\"Ticker\":\"BPOST\"}",
   "sorter": {}
}
```

__404 error__
![image](https://user-images.githubusercontent.com/3539605/102966775-d4534980-44f0-11eb-99ad-fe3b4acdb7b2.png)

**Comment by SamVanhoutte** [comment]
Maybe interesting to note: I am using the DurableEntityClient straight from my HttpTrigger in this project, so I am not having (yet) any Durable Orchestrations, so that might be related to the sequence diagram?  (just thinking aloud)

**Comment by scale-tone** [comment]
Hi @SamVanhoutte , thanks for reporting this!
I do confirm that I can repro.

Please, disregard the "Failed to load Sequence Diagram" description, it is irrelevant to the case (a typo in [the error handling logic](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.react/src/states/OrchestrationDetailsState.ts#L294)).

The cause seems to be some routing problem in Azure Functions, which is only reproducible on Linux (or inside a Linux container). When backend is running on Windows, it works fine.

Will do some further investigations and come back to you on this...

**Comment by scale-tone** [comment]
Not sure what was it (even testing on a Azure Linux image with Functions v2 did not reproduce, only was reproducible with Docker container), but switching to `mcr.microsoft.com/azure-functions/dotnet:3.0` as the base image in Dockerfile seemed to fix it. 

Pushed an updated image with the same tag (**scaletone/durablefunctionsmonitor:3.9**). 
@SamVanhoutte , can you please try to re-pull and validate?

**Comment by SamVanhoutte** [comment]
That seems to have fixed it.  Thanks for the quick fix !
