### ISSUE TITLE
Error when running version 4.0 in Azure , after deployment template

### ISSUE THREAD

**Issue by SamVanhoutte** [scale-tone/DurableFunctionsMonitor#54]
Hello, 

I wanted to try version 4.0 and verify the bugfix for issue #51 , but I get an exception in the developer tools, leaving the result pane empty for the same storage account & TaskHubName as I was running the 3.9.

Would you have an idea what could be causing this? 
Error information in the developer console of Edge:

```
DFM: accessToken is null, so using idToken.rawIdToken instead
registerServiceWorker.ts:86 Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://dfm-xxxx.azurewebsites.net/') with script ('https://dfm-xxxx.azurewebsites.net/service-worker.js'): ServiceWorker script evaluation failed
(anonymous) @ registerServiceWorker.ts:86
```

**Comment by scale-tone** [comment]
Hi @SamVanhoutte !

Those messages in Dev Console are unrelated (in fact, they're normal). Are you saying that you now get an entirely blank browser window and no any other visible error messages? If yes, it's really strange. Can you please paste a screenshot?

When that happens, are you navigating to the root URL? When DFM_HUB_NAME is set, root URL is expected to redirect you to a URL with that hub name at the end, e.g. to https://my-dfm-instance.azurewebsites.net/my-task-hub. Does that happen? Can you try to manually navigate to such a URL instead?

Could it be because the underlying instance was still under deployment? Can you try to refresh, especially by pressing Ctrl+F5? Does that help?

Also, please, note that if you re-deploy a new version to your *existing* Functions instance with 'Deploy to Azure' button, it might not automatically pick up the latest nuget package. For that to happen, the Functions instance might need to be manually restarted. Can you please ensure you see 'v4.0.0.0' in the browser tab title?

**Comment by SamVanhoutte** [comment]
FYI: I see the same behavior on the same task hub + storage account, when running locally from docker (fresh docker pull & new container)

> Are you saying that you now get an entirely blank browser window and no any other visible error messages? If yes, it's really strange. Can you please paste a screenshot?

Indeed, a screen without results (and I surely have active entities & functions in that taskhub).
<img width="1129" alt="Greenshot 2021-01-15 09 25 20" src="https://user-images.githubusercontent.com/3539605/104700022-da190500-5713-11eb-8ae1-c2316535de62.png">

> When that happens, are you navigating to the root URL? When DFM_HUB_NAME is set, root URL is expected to redirect you to a URL with that hub name at the end, e.g. to https://my-dfm-instance.azurewebsites.net/my-task-hub. Does that happen? Can you try to manually navigate to such a URL instead?

I have indeed configured a DFM_HUB_NAME and yes, it auto-redirects to the right location.

> Could it be because the underlying instance was still under deployment? Can you try to refresh, especially by pressing Ctrl+F5? Does that help?

I have forced refresh, also restart of the functions app.  

> Also, please, note that if you re-deploy a new version to your existing Functions instance with 'Deploy to Azure' button, it might not automatically pick up the latest nuget package. For that to happen, the Functions instance might need to be manually restarted. Can you please ensure you see 'v4.0.0.0' in the browser tab title?

I verified that it uses the 4.0.0.0 package and indeed, the title of the page is 4.0.0.0.  I actually removed the 3.9 instance of the app&plan, and deployed to a new one (with the same name, though).

Anything else you want me to look into, don't hesitate...

**Comment by scale-tone** [comment]
> Indeed, a screen without results

OK, so it's not an empty page, but simply no results being returned. In that case I'd suspect either a typo in  the TaskHub name (or in the conn string) or some specificity in that TaskHub name, which DFM fails to handle.

Can you please click on 
![image](https://user-images.githubusercontent.com/5447190/104712619-08eaa780-5723-11eb-9f46-7004610ee9d9.png)
and validate that you see the correct conn string and Task Hub name there?

Can you also try to remove that DFM_HUB_NAME setting and navigate to the root, to get the list of available TaskHubs? Is that list at least shown? Do you see your Task Hub in that list? Does that list look reasonable? When clicking on your Task Hub in that list, do you still don't get your orchestrations? Do you see any data in any other Task Hubs?

**Comment by SamVanhoutte** [comment]
Ow boy...  
I had taken the wrong connection string, pointing to my actual storage account, and not to the functions storage account. 
So yes, that typo was the case.

**Comment by SamVanhoutte** [comment]
Apologies & thanks for the support

**Comment by scale-tone** [comment]
Great, I hope, Liquid templates for your Entities also work now.
