### ISSUE TITLE
System.OutOfMemoryException from Huge Orchestration Activity count makes detail view non functional

### ISSUE THREAD

**Issue by drdamour** [scale-tone/DurableFunctionsMonitor#76]
we have a few orchestrations that spun up 10k+ activities.  fetching the activity history even with the runtime webhooks leads to OutOfMemory problems
![image](https://user-images.githubusercontent.com/1514496/111674678-e0922e80-87e1-11eb-8769-b47f7e9100eb.png)

but in dfmon it has a really unfortunate problem of building an unusable UX
![image](https://user-images.githubusercontent.com/1514496/111674778-ff90c080-87e1-11eb-9c1d-20ac949f164b.png)

i think it'd be nice if the UX could still function for terminate/purge etc commands even in this case.

one suggested approach might be to allow https://github.com/scale-tone/DurableFunctionsMonitor/blob/1d96852ce41b0638291a3685fa9cffd8e38ce511/durablefunctionsmonitor.dotnetbackend/Functions/Orchestration.cs#L224 to be wrapped with a secondary call to fetch without history (As this is the most likely offender) or maybe fetch history independently of the input/output status as hsitory is only needed for the more detailed tabs leaving the heart of the detailed view available

**Comment by scale-tone** [comment]
Yes, it would make perfect sense to fetch the execution history separately

**Comment by scale-tone** [comment]
Fixed in v4.3. Please, validate.

**Comment by zhilbug** [comment]
@scale-tone We are testing this change and seeing 11MB responses with over 4800 rows to **/a/p/i/usop1fap01tecsysmiddlewareintegrations/orchestrations('ced2acdf552c497cafc570ef76a5b5e0')/history?$top=200&$skip=0**. Maybe the $top=200 isn't working or something?
The UX is freezing including all the options being inactive.
![image](https://user-images.githubusercontent.com/10144597/114206902-0c07c500-9919-11eb-95b5-db080b206600.png)

Do you have any ideas here?

**Comment by scale-tone** [comment]
@zhilbug , from your screenshot I can see, that the basic orchestration fields were loaded successfully, and what happens now is that your execution history is being loaded. Because your history is huge, it takes quite a while to load it. Changing the page size ($top) sadly wouldn't speed it up, because Durable Functions SDK doesn't provide a method to load the execution history page by page, [only all or nothing](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/Functions/Orchestration.cs#L69).

But you always have an option to press 'Cancel' button and observe your instance without history.

The general recommendation is to avoid having orchestrations with such a huge execution history. Consider splitting them into suborchestrations or separate instances.

**Comment by zhilbug** [comment]
@scale-tone so when we have an orchestration this large or have an instance where it is stuck and not finishing, why wouldn't the options to terminate be active?  Do they require the history to be completely shown in order to have the ability to stop these? If on the details screen it requires that it have history, then why couldn't there be a way to do this from the previous listing screen to select and orchestration and terminate/purge?

**Comment by drdamour** [comment]
@scale-tone FWWI you can't even cancel out, the entire tab UX goes totally unresponsive. no doubt sub orchestration is the way to go, but just reporting that DF Mon gets totally  hunge in this case.  Maybe a pre-emptive too big check is in order?  the main issue is as @zhilbug pointed out you can't use the very useful terminate/purge actions when it gets in this state...which was the original issue with this ticket.

**Comment by scale-tone** [comment]
If you can't even cancel it, then it indeed looks like a rendering issue. Will need to fix it a little more...

**Comment by scale-tone** [comment]
Fixed in v4.4. Please, validate.

**Comment by scale-tone** [comment]
Assuming it finally works, I'll close this. Please, file other issues if anything else missing.

**Comment by chezlange** [comment]
After updating to v4.4, the response time was about 10-15 seconds for activities with a large number of events, whereas before it would timeout.  This appears to have fixed the issue.  Thanks!
